apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: x86
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-04d0f8531b987c660  # For x86_64 (Intel)
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet-cluster
  instanceProfile: KarpenterNodeInstanceProfile-opsfleet-cluster
  # role: "KarpenterNodeRole-opsfleet-cluster"
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: "50Gi"
      volumeType: gp3
      encrypted: true
      deleteOnTermination: true
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: arm64
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-0d093b852ddf6ad28  # For arm64 (Graviton)
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet-cluster
  instanceProfile: KarpenterNodeInstanceProfile-opsfleet-cluster
  # role: "KarpenterNodeRole-opsfleet-cluster"
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: "50Gi"
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true